ynot9042/Finals

back-end/README.md, front-end/public/index.html, front-end/src/App.css
Adding some font information in CSS and the link to the Google Font API in the index.html
=> adding font information

front-end/src/App.js, front-end/src/components/Button.js, front-end/src/styles/button.scss
Added button component with its relevant CSS
=> Implement button component with relevant css

front-end/src/App.scss, front-end/src/styles/navbar.scss
=> Add margin-top  to App class

front-end/src/Pages/Home.js, front-end/src/styles/homepage.scss
Fixed minor carousel bug and add effect.
=> Add carousel effects

front-end/src/Pages/Home.js
=> Add Autoplay to carousel

front-end/src/App.scss, front-end/src/Pages/Home.js, front-end/src/index.scss, front-end/src/styles/button.scss, front-end/src/styles/categoryitem.scss, front-end/src/styles/homepage.scss
=> Add css for home page

back-end/app.js, back-end/db/queries/artwork.js, back-end/routes/artwork.js, front-end/package-lock.json, front-end/src/App.js, front-end/src/Pages/Home.js, front-end/src/Pages/Product_description.js, front-end/src/context/dataContext.js
Implement independent access to product pages
=> Implement independent access to product pages

back-end/app.js, back-end/db/queries/artwork.js, back-end/routes/categoryItem.js, front-end/src/App.js, front-end/src/Pages/Category.js, front-end/src/Pages/Home.js, front-end/src/Pages/Product_description.js, front-end/src/components/CategoryItem.js, front-end/src/styles/artForCategory.scss, front-end/src/styles/productInfo.scss
Implement selecting all artwork for a specific category
=> Implement selecting all artwork for a specific category

front-end/package-lock.json, front-end/src/components/Header.js
Add login and register routes to navbar
=> Add login and register routes to navbar

back-end/app.js, back-end/db/queries/users.js, back-end/routes/userRegistration.js, front-end/src/Pages/Login.js, front-end/src/Pages/Register.js, front-end/src/styles/userAuth.scss
Users can now register and be added to the database
=> Implement user register feature

front-end/package-lock.json, front-end/src/Pages/Gallery.js, front-end/src/styles/gallery.scss
Updating Gallery and Adding some css
=> Updating Gallery and Adding some css

back-end/package-lock.json, back-end/package.json, back-end/routes/userRegistration.js, front-end/src/Pages/Register.js
Added bcrypt to hash user registration passwords
=> Implement hashed password

back-end/app.js, back-end/db/queries/users.js, back-end/routes/userLogin.js, front-end/src/Pages/Login.js, front-end/src/Pages/Register.js
Implement log in functionality
=> Implement log in functionality

front-end/package-lock.json, front-end/src/Pages/Category.js, front-end/src/Pages/Gallery.js
=> Delete / from img Src

front-end/package-lock.json, front-end/src/App.scss, front-end/src/Pages/Gallery.js, front-end/src/components/Header.js, front-end/src/components/Home.js, front-end/src/styles/gallery.scss
=> Fixed Gallery style bug

back-end/app.js, back-end/db/queries/users.js, back-end/routes/artists.js, back-end/routes/userSession.js, front-end/src/App.js, front-end/src/Pages/Artists.js, front-end/src/Pages/Categories.js, front-end/src/Pages/Category.js, front-end/src/components/ArtistItem.js, front-end/src/components/Header.js, front-end/src/styles/artistitem.scss, front-end/src/styles/homepage.scss
I updated the nav bar to reflect the current architecture and added an artists page following the categories page.
=> Update nav bar

back-end/db/queries/artwork.js, back-end/routes/profile.js, front-end/src/Pages/Profile.js, front-end/src/components/ViewProfile.js, front-end/src/styles/gallery.scss
adding handle delete art and moving user gallery to viewProfile component
=> minor bug fixes

front-end/src/Pages/Gallery.js, front-end/src/styles/gallery.scss
=> Fix Gallery Style bug

front-end/src/styles/artForCategory.scss
=> Fixed h1 padding issue

front-end/src/Pages/Home.js, front-end/src/styles/categoryitem.scss, front-end/src/styles/homepage.scss
fixed Swiper issue and changed gategory grid
=> fixed Swiper issue and changed gategory grid

front-end/src/Pages/EditArtwork.js, front-end/src/styles/editartwork.scss, front-end/src/styles/editprofile.scss, front-end/src/styles/profile.scss
edit h1 style in editprofile and changed editartwork design
=> edit h1 style in editprofile and changed editartwork design

front-end/src/App.scss, front-end/src/Pages/Home.js, front-end/src/styles/homepage.scss
Add media queries for home page and App css for top padding
=> Add media queries for home page and App css for top padding

front-end/src/components/Header.js, front-end/src/styles/navbar.scss
Edited responsive design for navbar
=> Edited responsive design for navbar

front-end/public/index.html, front-end/src/Pages/Confirmation.js, front-end/src/styles/artistitem.scss, front-end/src/styles/confirmation.scss, front-end/src/styles/homepage.scss, front-end/src/styles/variables.scss
changed font and some css stuff
=> changed font and some css stuff

front-end/src/styles/gallery.scss
=> edit gallery margin top
